FROM golang:1.18-bullseye

RUN deps="git curl ffmpeg python3" && \
    set -eux && \
    apt-get update && \
    apt-get install -y --no-install-recommends ${deps} && \
    rm -rf /var/lib/apt/lists/* && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    go install github.com/cosmtrek/air@latest

WORKDIR /root

CMD air
