FROM golang:1.18.0-alpine3.15

ARG PKGS

RUN deps="git curl ffmpeg python3 libc6-compat" && \
    set -euxo pipefail && \
    apk update && \
    apk add -q --progress --update --no-cache ${deps} && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    go install github.com/cosmtrek/air@latest

WORKDIR /root

CMD air
